version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=agro_producers_api_user
      - DB_PASSWORD=Nhaca70x07
      - DB_DATABASE=agro_producers_api
      - JWT_SECRET=nhaca
    volumes:
      - .:/app
    depends_on:
      - database
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=agro_producers_api_user
      - DB_PASSWORD=Nhaca70x07
      - DB_DATABASE=agro_producers_api
      - JWT_SECRET=nhaca
    command: ["yarn", "test"]
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: agro_producers_api_user
      POSTGRES_PASSWORD: Nhaca70x07
      POSTGRES_DB: agro_producers_api
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
