version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: ["yarn", "start:dev"]
    volumes:
      - .:/app
    depends_on:
      - database
  test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["yarn", "test"]
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
